import Head from "next/head";
import Image from "next/image";
import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";

import { type RouterOutputs, api } from "~/utils/api";
import { type NextPage } from "next";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import LoadingPage from "~/components/loading";

dayjs.extend(relativeTime);

const CreatePostWizard: NextPage = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full items-center gap-4">
      <Image
        src={user.imageUrl}
        alt="profile picture"
        width={100}
        height={100}
        className="h-14 w-14 rounded-full"
      />
      <input
        type="text"
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
      />
      <div>
        <SignOutButton />
      </div>
    </div>
  );
};

type PostWithUser = RouterOutputs["post"]["getAll"][number];

const PostView = ({ post, author }: PostWithUser) => {
  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <Image
        src={author.profilePicture}
        alt="profile image"
        width={300}
        height={300}
        className="h-14 w-14 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex items-center gap-1 font-semibold text-slate-300">
          <span>{`@${author.username}`}</span>
          <span className=" text-sm text-slate-400">
            {" "}
            - {dayjs(post.createdAt).fromNow()}
          </span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { data, isLoading } = api.post.getAll.useQuery();
  const user = useUser();

  if (isLoading) return <LoadingPage/>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-200 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4 ">
            {user.isSignedIn ? (
              <CreatePostWizard />
            ) : (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {data.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
