import type { GetStaticProps, NextPage } from "next";
import { api } from "src/utils/api";
import { PageLayout } from "~/components/layout";
import { generateSSGHelper } from "~/utils/helpers";
import PostView from "~/components/postView";
import Head from "next/head";

const SinglePost: NextPage<{ id: string }> = ({ id }) => {
  const { data } = api.post.getById.useQuery({
    id,
  });
  console.log(data);
  if (!data) return <div>404</div>;

  return (
    <>
      <Head>
        <title>{data.post.content} - @{data.author.username}</title>
        <meta name="description" content="Generated by CT3A" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <PostView {...data} />
      </PageLayout>
    </>
  );
};


export const getStaticProps: GetStaticProps = async (context) => {
  const ssg = generateSSGHelper();

  const id = context.params?.id;

  if (typeof id !== "string") throw new Error("id is not a string");

  await ssg.post.getById.prefetch({ id });

  return {
    props: {
      id,
    },
  };
};

export const getStaticPaths = () => {
  return { paths: [], fallback: "blocking" };
};

export default SinglePost;
