import { type NextPage } from "next";
import Head from "next/head";

const SinglePost: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by CT3A" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default SinglePost;
